# Generated by Django 3.2.24 on 2024-04-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0003_auto_20240419_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '大一'), (2, '大二'), (3, '大三'), (4, '大四')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.IntegerField(blank=True),
        ),
    ]
