# Generated by Django 3.2.24 on 2024-04-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0005_alter_profile_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.IntegerField(choices=[(0, '未知'), (1, '大一'), (2, '大二'), (3, '大三'), (4, '大四')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.IntegerField(default=0),
        ),
    ]
