# Generated by Django 3.2.24 on 2024-05-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0008_auto_20240520_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(default='', max_length=20),
        ),
    ]
