# Generated by Django 3.2.24 on 2024-06-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0015_aboutarticles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutarticles',
            name='like',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutarticles',
            name='star',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
