# Generated by Django 3.2.24 on 2024-06-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0019_auto_20240606_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutarticles',
            name='courseFollow',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutarticles',
            name='majorFollow',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutarticles',
            name='schoolFollow',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
