# Generated by Django 3.2.24 on 2024-06-09 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0020_auto_20240609_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutarticles',
            old_name='courseFollow',
            new_name='courseFollows',
        ),
        migrations.RenameField(
            model_name='aboutarticles',
            old_name='majorFollow',
            new_name='majorFollows',
        ),
        migrations.RenameField(
            model_name='aboutarticles',
            old_name='schoolFollow',
            new_name='schoolFollows',
        ),
    ]
