# Generated by Django 3.2.24 on 2024-06-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlepost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='hates',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
