# Generated by Django 3.2.24 on 2024-06-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlepost_hates'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='course',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='articlepost',
            name='major',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='articlepost',
            name='school',
            field=models.IntegerField(default=-1),
        ),
    ]
