# Generated by Django 3.2.24 on 2024-06-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20240606_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='course',
            field=models.CharField(default=-1, max_length=10),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='major',
            field=models.CharField(default=-1, max_length=10),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='school',
            field=models.CharField(default=-1, max_length=10),
        ),
    ]
